# Generated by Django 3.1.1 on 2020-09-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
                ('currency', models.TextField()),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accountsoperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'accountsoperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Annualtargets',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'annualtargets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'banks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField()),
            ],
            options={
                'db_table': 'concepts',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditcards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('deferred', models.BooleanField()),
                ('maximumbalance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('active', models.BooleanField()),
                ('number', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'creditcards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Creditcardsoperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('paid_datetime', models.DateTimeField(blank=True, null=True)),
                ('accountsoperations_id', models.BigIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'creditcardsoperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=100)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dps', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('accountsoperations_id', models.IntegerField(blank=True, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('currency_conversion', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'db_table': 'dividends',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('paydate', models.DateField()),
            ],
            options={
                'db_table': 'dps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimationsDps',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('estimation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_estimation', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('manual', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estimations_dps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstimationsEps',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('estimation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_estimation', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('manual', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estimations_eps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('global_field', models.TextField(db_column='global', primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'globals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('selling_price', models.DecimalField(decimal_places=6, max_digits=100)),
                ('selling_expiration', models.DateField(blank=True, null=True)),
                ('daily_adjustment', models.BooleanField()),
                ('balance_percentage', models.DecimalField(decimal_places=6, max_digits=18)),
            ],
            options={
                'db_table': 'investments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investmentsaccountsoperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepts_id', models.IntegerField()),
                ('operationstypes_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('accounts_id', models.IntegerField()),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('investmentsoperations_id', models.IntegerField()),
                ('investments_id', models.IntegerField()),
            ],
            options={
                'db_table': 'investmentsaccountsoperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Investmentsoperations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('show_in_ranges', models.BooleanField(blank=True, null=True)),
                ('currency_conversion', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
            options={
                'db_table': 'investmentsoperations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leverages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('multiplier', models.DecimalField(decimal_places=65535, max_digits=65535)),
            ],
            options={
                'db_table': 'leverages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operationstypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'operationstypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('removed', models.DateField(blank=True, null=True)),
                ('executed', models.DateField(blank=True, null=True)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=100)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('short', models.BooleanField()),
            ],
            options={
                'db_table': 'opportunities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expiration', models.DateField()),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('executed', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('isin', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('agrupations', models.TextField(blank=True, null=True)),
                ('web', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField()),
                ('pci', models.CharField(max_length=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('obsolete', models.BooleanField()),
                ('tickers', models.TextField(blank=True, null=True)),
                ('high_low', models.BooleanField(blank=True, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productstypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'productstypes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('quote', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'quotes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.TextField(blank=True, null=True)),
                ('starting', models.DateTimeField(blank=True, null=True)),
                ('ending', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simulations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('before', models.IntegerField()),
                ('after', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'splits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('investments', models.TextField(blank=True, null=True)),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'strategies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stockmarkets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(max_length=5)),
                ('starts', models.TimeField()),
                ('closes', models.TimeField()),
                ('starts_futures', models.TimeField()),
                ('closes_futures', models.TimeField()),
                ('zone', models.TextField()),
            ],
            options={
                'db_table': 'stockmarkets',
                'managed': True,
            },
        ),
    ]
