# Generated by Django 4.1.4 on 2023-01-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField()),
                ('number', models.CharField(blank=True, max_length=24, null=True)),
                ('currency', models.TextField()),
                ('decimals', models.IntegerField()),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Accountsoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.accounts')),
            ],
            options={
                'db_table': 'accountsoperations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Annualtargets',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'annualtargets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'banks',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Concepts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('editable', models.BooleanField()),
            ],
            options={
                'db_table': 'concepts',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Creditcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('deferred', models.BooleanField()),
                ('maximumbalance', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('active', models.BooleanField()),
                ('number', models.TextField(blank=True, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.accounts')),
            ],
            options={
                'db_table': 'creditcards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Globals',
            fields=[
                ('global_field', models.TextField(db_column='global', primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'globals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
                ('selling_price', models.DecimalField(decimal_places=6, max_digits=100)),
                ('selling_expiration', models.DateField(blank=True, null=True)),
                ('daily_adjustment', models.BooleanField()),
                ('balance_percentage', models.DecimalField(decimal_places=6, max_digits=18)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.accounts')),
            ],
            options={
                'db_table': 'investments',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Leverages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
            options={
                'db_table': 'leverages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operationstypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'operationstypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('isin', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('agrupations', models.TextField(blank=True, null=True)),
                ('web', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField()),
                ('pci', models.CharField(choices=[('c', 'Call'), ('p', 'Put'), ('i', 'Inline')], max_length=1)),
                ('comment', models.TextField(blank=True, null=True)),
                ('obsolete', models.BooleanField()),
                ('ticker_google', models.TextField(blank=True, null=True)),
                ('ticker_yahoo', models.TextField(blank=True, null=True)),
                ('ticker_morningstar', models.TextField(blank=True, null=True)),
                ('ticker_quefondos', models.TextField(blank=True, null=True)),
                ('ticker_investingcom', models.TextField(blank=True, null=True)),
                ('decimals', models.IntegerField(blank=True, null=True)),
                ('leverages', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.leverages')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productstypes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'db_table': 'productstypes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Simulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('database', models.TextField(blank=True, null=True)),
                ('starting', models.DateTimeField(blank=True, null=True)),
                ('ending', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('creation', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'simulations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stockmarkets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country', models.CharField(max_length=5)),
                ('starts', models.TimeField()),
                ('closes', models.TimeField()),
                ('starts_futures', models.TimeField()),
                ('closes_futures', models.TimeField()),
                ('zone', models.TextField()),
            ],
            options={
                'db_table': 'stockmarkets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Strategies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('investments', models.TextField()),
                ('dt_from', models.DateTimeField(blank=True, null=True)),
                ('dt_to', models.DateTimeField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Pairs in same account'), (2, 'Product ranges'), (3, 'Generic')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('additional1', models.IntegerField(blank=True, null=True)),
                ('additional2', models.IntegerField(blank=True, null=True)),
                ('additional3', models.IntegerField(blank=True, null=True)),
                ('additional4', models.IntegerField(blank=True, null=True)),
                ('additional5', models.IntegerField(blank=True, null=True)),
                ('additional6', models.IntegerField(blank=True, null=True)),
                ('additional7', models.IntegerField(blank=True, null=True)),
                ('additional8', models.IntegerField(blank=True, null=True)),
                ('additional9', models.IntegerField(blank=True, null=True)),
                ('additional10', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'strategies',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Splits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('before', models.IntegerField()),
                ('after', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'splits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('quote', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'quotes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productspairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='moneymoney.products')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moneymoney.products')),
            ],
            options={
                'db_table': 'productspairs',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='products',
            name='productstypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.productstypes'),
        ),
        migrations.AddField(
            model_name='products',
            name='stockmarkets',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.stockmarkets'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expiration', models.DateField()),
                ('shares', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('executed', models.DateTimeField(blank=True, null=True)),
                ('investments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investments')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Opportunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('removed', models.DateField(blank=True, null=True)),
                ('executed', models.DateField(blank=True, null=True)),
                ('entry', models.DecimalField(decimal_places=2, max_digits=100)),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('stoploss', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('short', models.BooleanField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'opportunities',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investmentsoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=6, max_digits=100)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=100)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=100)),
                ('datetime', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('show_in_ranges', models.BooleanField()),
                ('currency_conversion', models.DecimalField(decimal_places=10, max_digits=30)),
                ('investments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investments')),
                ('operationstypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.operationstypes')),
            ],
            options={
                'db_table': 'investmentsoperations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Investmentsaccountsoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.accounts')),
                ('concepts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.concepts')),
                ('investments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investments')),
                ('investmentsoperations', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investmentsoperations')),
                ('operationstypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.operationstypes')),
            ],
            options={
                'db_table': 'investmentsaccountsoperations',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='investments',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products'),
        ),
        migrations.CreateModel(
            name='Dps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gross', models.DecimalField(decimal_places=6, max_digits=18)),
                ('paydate', models.DateField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'dps',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dividends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross', models.DecimalField(decimal_places=2, max_digits=100)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=100)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('dps', models.DecimalField(blank=True, decimal_places=6, max_digits=100, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('currency_conversion', models.DecimalField(decimal_places=6, max_digits=10)),
                ('accountsoperations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.accountsoperations')),
                ('concepts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.concepts')),
                ('investments', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investments')),
            ],
            options={
                'db_table': 'dividends',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Creditcardsoperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('paid_datetime', models.DateTimeField(blank=True, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('accountsoperations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid_accountsoperations', to='moneymoney.operationstypes')),
                ('concepts', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.concepts')),
                ('creditcards', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.creditcards')),
                ('operationstypes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.operationstypes')),
            ],
            options={
                'db_table': 'creditcardsoperations',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='concepts',
            name='operationstypes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.operationstypes'),
        ),
        migrations.AddField(
            model_name='accountsoperations',
            name='concepts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.concepts'),
        ),
        migrations.AddField(
            model_name='accountsoperations',
            name='operationstypes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.operationstypes'),
        ),
        migrations.AddField(
            model_name='accounts',
            name='banks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accounts', to='moneymoney.banks'),
        ),
        migrations.CreateModel(
            name='EstimationsEps',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('estimation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_estimation', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('manual', models.BooleanField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'estimations_eps',
                'managed': True,
                'unique_together': {('year', 'products')},
            },
        ),
        migrations.CreateModel(
            name='EstimationsDps',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('estimation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_estimation', models.DateField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('manual', models.BooleanField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'estimations_dps',
                'managed': True,
                'unique_together': {('year', 'products')},
            },
        ),
    ]
