# Generated by Django 3.1.1 on 2020-09-22 06:39

from datetime import time
from django.db import migrations
from money.models import Stockmarkets

def add_stockmarkets(apps, schema_editor):
    s=Stockmarkets(id=1,name="Madrid Stock Exchange", country="es", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Madrid")
    s.save()
    s=Stockmarkets(id=11,name="Belgium Stock Exchange", country="be", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(17, 40), zone="Europe/Brussels")
    s.save()
    s=Stockmarkets(id=12,name="Amsterdam Stock Exchange", country="nl", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(22, 0), zone="Europe/Amsterdam")
    s.save()
    s=Stockmarkets(id=13,name="Dublin Stock Exchange", country="ie", starts=time(8, 0), closes=time(16, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Dublin")
    s.save()
    s=Stockmarkets(id=14,name="Helsinki Stock Exchange", country="fi", starts=time(9, 0), closes=time(18, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Helsinki")
    s.save()
    s=Stockmarkets(id=6,name="Milan Stock Exchange", country="it", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Rome")
    s.save()
    s=Stockmarkets(id=7,name="Tokyo Stock Exchange", country="jp", starts=time(9, 0), closes=time(15, 8), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Asia/Tokyo")
    s.save()
    s=Stockmarkets(id=5,name="Frankfurt Stock Exchange", country="de", starts=time(9, 0), closes=time(17, 38), starts_futures=time(1, 0), closes_futures=time(22, 0), zone="Europe/Berlin")
    s.save()
    s=Stockmarkets(id=2,name="NYSE Stock Exchange", country="us", starts=time(9, 30), closes=time(16, 38), starts_futures=time(0, 0), closes_futures=time(23, 59), zone="America/New_York")
    s.save()
    s=Stockmarkets(id=10,name="Europe Stock Exchange", country="ue", starts=time(9, 0), closes=time(17, 38), starts_futures=time(1, 0), closes_futures=time(22, 0), zone="Europe/Brussels")
    s.save()
    s=Stockmarkets(id=9,name="Lisbon Stock Exchange", country="pt", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(17, 40), zone="Europe/Lisbon")
    s.save()
    s=Stockmarkets(id=4,name="London Stock Exchange", country="en", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/London")
    s.save()
    s=Stockmarkets(id=8,name="Hong Kong Stock Exchange", country="cn", starts=time(9, 30), closes=time(16, 8), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Asia/Hong_Kong")
    s.save()
    s=Stockmarkets(id=3,name="Paris Stock Exchange", country="fr", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(22, 0), zone="Europe/Paris")
    s.save()
    s=Stockmarkets(id=15,name="Not listed on official markets", country="earth", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Madrid")
    s.save()
    s=Stockmarkets(id=16,name="AMEX Stock Exchange", country="us", starts=time(9, 30), closes=time(16, 38), starts_futures=time(0, 0), closes_futures=time(23, 59), zone="America/New_York")
    s.save()
    s=Stockmarkets(id=17,name="Nasdaq Stock Exchange", country="us", starts=time(9, 30), closes=time(16, 38), starts_futures=time(0, 0), closes_futures=time(23, 59), zone="America/New_York")
    s.save()
    s=Stockmarkets(id=18,name="Luxembourg Stock Exchange", country="lu", starts=time(9, 0), closes=time(17, 38), starts_futures=time(8, 0), closes_futures=time(20, 0), zone="Europe/Luxembourg")
    s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_stockmarkets)
    ]
