# Generated by Django 4.0.4 on 2022-06-01 06:40

from django.db import migrations
from django.contrib.auth.models import Group

def apply_migration(apps, schema_editor):
    gr=Group.objects.create(name="CatalogManager")
    gr.save()

class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0002_auto_20230107_2039'),
    ]

    operations = [
        migrations.RunPython(apply_migration)
    ]
