# Generated by Django 3.1.3 on 2020-11-15 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20200922_0639'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investments',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'managed': False, 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='strategies',
            options={'managed': False, 'ordering': ['name']},
        ),
    ]
