# Generated by Django 4.1.4 on 2023-01-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0003_add_group_catalog_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarkets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
