# Generated by Django 4.1.4 on 2023-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0005_alter_leverages_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstypes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
