# Generated by Django 4.1.4 on 2023-01-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0006_alter_productstypes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
