# Generated by Django 4.1.5 on 2023-01-14 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0007_alter_quotes_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsoperations',
            name='operationstypes',
        ),
    ]
