# Generated by Django 4.1.5 on 2023-01-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0010_auto_20230114_1314'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Investmentsaccountsoperations',
        ),
    ]
