# Generated by Django 4.1.5 on 2023-01-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0011_delete_investmentsaccountsoperations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsoperations',
            name='operationstypes',
        ),
    ]
