# Generated by Django 4.1.5 on 2023-01-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0012_remove_accountsoperations_operationstypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcardsoperations',
            name='operationstypes',
        ),
    ]
