# Generated by Django 4.1.5 on 2023-01-14 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0013_remove_creditcardsoperations_operationstypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardsoperations',
            name='accountsoperations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid_accountsoperations', to='moneymoney.accountsoperations'),
        ),
    ]
