# Generated by Django 4.1.5 on 2023-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0014_alter_creditcardsoperations_accountsoperations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstypes',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
