# Generated by Django 4.1.5 on 2023-01-15 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('moneymoney', '0015_alter_operationstypes_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('currency', models.CharField(default='EUR', max_length=4)),
                ('zone', models.CharField(default='Europe/Madrid', max_length=50)),
                ('investing_com_url', models.TextField(blank=True, null=True)),
                ('investing_com_cookie', models.TextField(blank=True, null=True)),
                ('investing_com_referer', models.TextField(blank=True, null=True)),
                ('invest_amount_1', models.DecimalField(decimal_places=6, default=2500, max_digits=30)),
                ('invest_amount_2', models.DecimalField(decimal_places=6, default=3500, max_digits=30)),
                ('invest_amount_3', models.DecimalField(decimal_places=6, default=7800, max_digits=30)),
                ('invest_amount_4', models.DecimalField(decimal_places=6, default=7800, max_digits=30)),
                ('invest_amount_5', models.DecimalField(decimal_places=6, default=7800, max_digits=30)),
                ('favorites', models.ManyToManyField(to='moneymoney.products')),
            ],
            options={
                'db_table': 'profiles',
                'managed': True,
            },
        ),
    ]
