# Generated by Django 4.1.5 on 2023-01-15 08:48

from django.db import migrations

from django.contrib.auth.models import User



def create_missing_profiles(apps, schema_editor):

    User=apps.get_model('auth', 'User')
    Profile=apps.get_model('moneymoney', 'Profile')
    for user in User.objects.all():
        try:
            user.profile
        except:
            p=Profile()
            p.user=user
            p.save()


class Migration(migrations.Migration):
    dependencies = [
        ('moneymoney', '0016_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles)

    ]
