# Generated by Django 4.1.5 on 2023-01-15 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0017_auto_20230115_0848_create_missing_profiles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Globals',
        ),
    ]
