# Generated by Django 4.1.5 on 2023-01-15 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0018_delete_globals'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Annualtargets',
        ),
    ]
