# Generated by Django 4.1.5 on 2023-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0019_delete_annualtargets'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opportunities',
        ),
    ]
