# Generated by Django 4.1.5 on 2023-01-15 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0020_delete_opportunities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simulations',
        ),
    ]
