# Generated by Django 4.1.5 on 2023-01-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0021_delete_simulations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstimationsEps',
        ),
    ]
