# Generated by Django 4.1.5 on 2023-01-15 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0022_delete_estimationseps'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstimationsDps',
            new_name='OldEstimationsDps',
        ),
        migrations.AlterModelTable(
            name='oldestimationsdps',
            table='old_estimations_dps',
        ),
    ]
