# Generated by Django 4.1.5 on 2023-01-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0023_rename_estimationsdps_oldestimationsdps_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimationsDps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('estimation', models.DecimalField(decimal_places=6, max_digits=18)),
                ('date_estimation', models.DateField(blank=True, null=True)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products')),
            ],
            options={
                'db_table': 'estimations_dps',
                'managed': True,
            },
        ),
    ]
