# Generated by Django 4.1.5 on 2023-01-15 16:45

from django.db import migrations


def migrate_estimations_dps(apps, schema_editor):

    OldEDPS=apps.get_model('moneymoney', 'OldEstimationsDPS')
    EDPS=apps.get_model('moneymoney', 'EstimationsDPS')
    for old in OldEDPS.objects.all():
        new=EDPS()
        new.year=old.year
        new.estimation=old.estimation
        new.date_estimation=old.date_estimation
        new.products=old.products
        new.save()



class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0024_estimationsdps'),
    ]

    operations = [
        migrations.RunPython(migrate_estimations_dps)
    ]
