# Generated by Django 4.1.5 on 2023-01-15 16:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0025_auto_20230115_1645_migrating_old_estimations_dps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimationsdps',
            name='date_estimation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='estimationsdps',
            name='estimation',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.DeleteModel(
            name='OldEstimationsDps',
        ),
    ]
