# Generated by Django 4.1.5 on 2023-01-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0026_alter_estimationsdps_date_estimation_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estimationsdps',
            table='estimations_dps',
        ),
    ]
