# Generated by Django 4.1.5 on 2023-01-22 05:50

# There are functions that uses integer instead of bigint. New databases uses bigint by default
# I convert tables id to integer to allow backwards compatibilyty until django upgrades all to bigint automatically

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0028_alter_orders_price'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE public.accounts ALTER COLUMN id TYPE integer"),
        migrations.RunSQL("ALTER TABLE public.investments ALTER COLUMN id TYPE integer")
    ]
