# Generated by Django 4.1.5 on 2023-01-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0029_auto_20230122_0550_bigint_to_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annual_gains_target',
            field=models.DecimalField(decimal_places=6, default=4, max_digits=30),
        ),
    ]
