# Generated by Django 4.1.7 on 2023-02-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0032_alter_orders_expiration'),
    ]

    operations = [
        migrations.RunSQL("""
CREATE OR REPLACE FUNCTION public.currency_factor(at_datetime timestamp with time zone, currency_from text, currency_to text)
 RETURNS numeric
 LANGUAGE plpgsql
AS $function$
DECLARE
    factor NUMERIC;
BEGIN
    IF currency_from = currency_to THEN
        factor:=1;
    ELSIF currency_from = 'EUR' AND currency_to = 'USD' THEN
        select quote INTO factor from quote(-74747, at_datetime);
    ELSIF currency_from = 'USD' AND currency_to = 'EUR' THEN
        select quote INTO factor from quote(-74747, at_datetime);
        IF factor = 0 THEN
            factor:=NULL;
        ELSE
            factor:=1/factor;
        END IF;
    END IF;
    IF factor IS NULL THEN return NULL; ELSE return factor; END IF;
END;
$function$
""")
    ]
