# Generated by Django 4.1.7 on 2023-02-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0033_function_currency_factor_invert_ids'),
    ]

    operations = [
        migrations.RunSQL("""drop function if exists public.total_balance;"""),
        migrations.RunSQL("""
CREATE OR REPLACE FUNCTION public.pl_total_balance(p_at_datetime timestamp with time zone, user_currency text)
 RETURNS text
 LANGUAGE plpython3u
AS $function$
from decimal import Decimal
from json import dumps,loads
from moneymoney_pl.core import MyDjangoJSONEncoder

plan_accounts=plpy.prepare('SELECT * from  accounts_balance($1,$2)',["timestamp with time zone","text"])
accounts=plpy.execute(plan_accounts, (p_at_datetime,user_currency))
accounts_user=accounts[0]['accounts_balance']

plan_investments=plpy.prepare('SELECT * FROM pl_investment_operations($1,$2,$3,$4,$5,$6)',["timestamp with time zone","text","integer[]","boolean","boolean","boolean"])
investments=loads(plpy.execute(plan_investments,(p_at_datetime, user_currency, None, False, False, True))[0]["pl_investment_operations"])

r= { 
    "accounts_user": accounts_user, 
    "investments_user": investments["sum_total_io_current"]["balance_user"],
    "total_user": accounts_user+Decimal(investments["sum_total_io_current"]["balance_user"]),
    "investments_invested_user": investments["sum_total_io_current"]["invested_user"],
    },

return dumps(r, cls=MyDjangoJSONEncoder)
$function$;""")
    ]
