# Generated by Django 4.1.7 on 2023-03-26 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0035_new_plio_functions'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='decimals',
            field=models.IntegerField(default=6),
        ),
    ]
