# Generated by Django 4.1.7 on 2023-04-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0036_investments_decimals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentsoperations',
            name='show_in_ranges',
        ),
    ]
