# Generated by Django 4.1.7 on 2023-04-07 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0037_remove_investmentsoperations_show_in_ranges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FastOperationsCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=6, max_digits=30)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
