# Generated by Django 4.1.7 on 2023-04-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0038_fastoperationscoverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastoperationscoverage',
            name='investments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.investments'),
            preserve_default=False,
        ),
    ]
