# Generated by Django 5.0.2 on 2024-03-05 22:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0042_removing_allfunctions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accountstransfers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "commission",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "ao_commission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ao_commission",
                        to="moneymoney.accountsoperations",
                    ),
                ),
                (
                    "ao_destiny",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ao_destiny",
                        to="moneymoney.accountsoperations",
                    ),
                ),
                (
                    "ao_origin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ao_origin",
                        to="moneymoney.accountsoperations",
                    ),
                ),
                (
                    "destiny",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destiny",
                        to="moneymoney.accounts",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin",
                        to="moneymoney.accounts",
                    ),
                ),
            ],
            options={
                "db_table": "accountstransfers",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="accountsoperations",
            name="associated_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="moneymoney.accountstransfers",
            ),
        ),
    ]
