# Generated by Django 5.0.2 on 2024-03-16 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0044_convert_old_transfers"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsoperations",
            name="associated_cc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.creditcards",
            ),
        ),
        migrations.AddField(
            model_name="accountsoperations",
            name="associated_io",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.investmentsoperations",
            ),
        ),
        migrations.AlterField(
            model_name="dividends",
            name="accountsoperations",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.accountsoperations",
            ),
        ),
    ]
