# Generated by Django 5.0.2 on 2024-03-16 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0045_accountsoperations_associated_cc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountsoperations",
            name="associated_io",
        ),
        migrations.AddField(
            model_name="investmentsoperations",
            name="associated_ao",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.accountsoperations",
            ),
        ),
    ]
