# Generated by Django 5.0.3 on 2024-03-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0047_convert_old_io_associated_ao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="strategies",
            old_name="investments",
            new_name="old_investments",
        ),
        migrations.AddField(
            model_name="strategies",
            name="investments",
            field=models.ManyToManyField(to="moneymoney.investments"),
        ),
    ]
