# Generated by Django 5.0.3 on 2024-03-28 06:11

from django.db import migrations
from tqdm import tqdm


def convert_investments_ids_to_m2m_investments(apps, schema_editor):
    Strategies=apps.get_model('moneymoney', 'Strategies')
    Investments=apps.get_model('moneymoney', 'Investments')

    for strategy in tqdm(Strategies.objects.all()):
        investments_ids=eval(f"[{strategy.old_investments}]")
        # Checks investments exists
        investments_ids_exist=[]
        for id in investments_ids:
            if Investments.objects.filter(pk=id).exists():
                investments_ids_exist.append(id)
            else:
                print ("Investment doesn't exist",  id)
        strategy.investments.add(*investments_ids_exist)

class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0048_strategies_old_investments_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_investments_ids_to_m2m_investments), 
    ]
