# Generated by Django 5.0.3 on 2024-03-28 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0049_strategies_investments_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategies",
            name="old_investments",
        ),
    ]
