# Generated by Django 5.0.3 on 2024-03-29 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moneymoney", "0050_remove_strategies_old_investments"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentsRecomendationMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductsStrategies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StrategiesTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "managed": True,
            },
        ),
        migrations.RenameField(
            model_name="strategies",
            old_name="type",
            new_name="oldtype"
        ),
        migrations.AddField(
            model_name="strategies",
            name="recomendation_method",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.investmentsrecomendationmethods",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="products",
            name="strategy",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.productsstrategies",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="strategies",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.strategiestypes",
            ),
        ),
    ]
