# Generated by Django 5.0.4 on 2024-04-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0050_remove_strategies_old_investments"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductsStrategies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
            ],
            options={
                "managed": True,
            },
        ),
    ]
