# Generated by Django 5.0.4 on 2024-04-28 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0051_productsstrategies"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="productsstrategies",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.productsstrategies",
            ),
            preserve_default=False,
        ),
    ]
