# Generated by Django 5.0.4 on 2024-04-28 05:45

import django.db.models.deletion
from django.db import migrations, models


def add_productsstrategies_values(apps, schema_editor):
    ProductsStrategies=apps.get_model('moneymoney', 'ProductsStrategies')
    
    list_=[]
    list_.append(ProductsStrategies(name="Call"))
    list_.append(ProductsStrategies(name="Put"))
    list_.append(ProductsStrategies(name="Inline"))
    ProductsStrategies.objects.bulk_create(list_)
    
class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0051_productsstrategies"),
    ]

    operations = [
        migrations.RunPython(add_productsstrategies_values), 
        migrations.AddField(
            model_name="products",
            name="productsstrategies",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.productsstrategies",
            ),
            preserve_default=False,
        ),
    ]
