# Generated by Django 5.0.4 on 2024-04-28 05:46

from django.db import migrations

def convert_pci_to_productsstrategies(apps, schema_editor):
    Products=apps.get_model('moneymoney', 'Products')

    Products.objects.filter(pci="c").update(productsstrategies_id=1)
    Products.objects.filter(pci="p").update(productsstrategies_id=2)
    Products.objects.filter(pci="i").update(productsstrategies_id=3)
   
class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0052_products_productsstrategies"),
    ]

    operations = [
        migrations.RunPython(convert_pci_to_productsstrategies), 
    ]
