# Generated by Django 5.1.6 on 2025-02-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0055_currency_mandatory_and_in_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategies",
            name="accounts",
            field=models.ManyToManyField(blank=True, to="moneymoney.accounts"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="investments",
            field=models.ManyToManyField(blank=True, to="moneymoney.investments"),
        ),
        migrations.AlterField(
            model_name="strategies",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Pairs in same account"),
                    (2, "Product ranges"),
                    (3, "Generic"),
                    (4, "Fast operations"),
                ]
            ),
        ),
    ]
