# Generated by Django 5.2.1 on 2025-05-27 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moneymoney",
            "0056_strategies_accounts_alter_strategies_investments_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NewStrategies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("dt_from", models.DateTimeField()),
                ("dt_to", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Pairs in same account"),
                            (2, "Product ranges"),
                            (3, "Generic"),
                            (4, "Fast operations"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "new_strategies",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StrategiesFastOperations",
            fields=[
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="moneymoney.newstrategies",
                    ),
                ),
                ("accounts", models.ManyToManyField(to="moneymoney.accounts")),
            ],
            options={
                "db_table": "strategies_fast_operations",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StrategiesGeneric",
            fields=[
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="moneymoney.newstrategies",
                    ),
                ),
                ("investments", models.ManyToManyField(to="moneymoney.investments")),
            ],
            options={
                "db_table": "strategies_generic",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StrategiesPairsInSameAccount",
            fields=[
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="moneymoney.newstrategies",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="moneymoney.accounts",
                    ),
                ),
                (
                    "better_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="better_product",
                        to="moneymoney.products",
                    ),
                ),
                (
                    "worse_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="worse_product",
                        to="moneymoney.products",
                    ),
                ),
            ],
            options={
                "db_table": "strategies_pairs_in_same_account",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StrategiesProductsRange",
            fields=[
                (
                    "strategy",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="moneymoney.newstrategies",
                    ),
                ),
                (
                    "percentage_between_ranges",
                    models.DecimalField(decimal_places=6, max_digits=100),
                ),
                (
                    "percentage_gains",
                    models.DecimalField(decimal_places=6, max_digits=100),
                ),
                ("amount", models.DecimalField(decimal_places=6, max_digits=100)),
                (
                    "recomendation_method",
                    models.IntegerField(
                        choices=[
                            (1, "All"),
                            (2, "SMA 10, 50, 200"),
                            (3, "SMA 100"),
                            (4, "Strict SMA 10, 50, 200"),
                            (5, "Strict SMA 100"),
                            (6, "Strict SMA 10, 100"),
                            (7, "None"),
                            (8, "SMA 10"),
                            (9, "SMA 5"),
                        ]
                    ),
                ),
                ("only_first", models.BooleanField()),
                ("investments", models.ManyToManyField(to="moneymoney.investments")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="moneymoney.products",
                    ),
                ),
            ],
            options={
                "db_table": "strategies_products_range",
                "managed": True,
            },
        ),
    ]
