# Generated by Django 5.2.1 on 2025-06-14 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0058_migrate_strategies_to_newstrategies"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Strategies",
        ),
    ]
