# Generated by Django 5.2.1 on 2025-06-14 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0059_delete_strategies"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="NewStrategies",
            new_name="Strategies",
        ),
        migrations.AlterModelTable(
            name="strategies",
            table="strategies",
        ),
    ]
