# Generated by Django 5.2.3 on 2025-09-03 10:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0060_rename_newstrategies_strategies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategiesproductsrange",
            name="recomendation_method",
            field=models.IntegerField(
                choices=[
                    (1, "All"),
                    (2, "SMA 10, 50, 200"),
                    (3, "SMA 100"),
                    (4, "Strict SMA 10, 50, 200"),
                    (5, "Strict SMA 100"),
                    (6, "Strict SMA 10, 100"),
                    (7, "None"),
                    (8, "SMA 10"),
                    (9, "SMA 5"),
                    (10, "HMA 10"),
                ]
            ),
        ),
        migrations.CreateModel(
            name="Investmentstransfers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_origin", models.DateTimeField()),
                (
                    "shares_origin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "price_origin",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "commission_origin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "taxes_origin",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency_conversion_origin",
                    models.DecimalField(
                        decimal_places=10,
                        default=1,
                        max_digits=30,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("datetime_destiny", models.DateTimeField()),
                (
                    "shares_destiny",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "price_destiny",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "commission_destiny",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "taxes_destiny",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=100,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "currency_conversion_destiny",
                    models.DecimalField(
                        decimal_places=10,
                        default=1,
                        max_digits=30,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "investments_destiny",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destiny",
                        to="moneymoney.investments",
                    ),
                ),
                (
                    "investments_origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="origin",
                        to="moneymoney.investments",
                    ),
                ),
            ],
            options={
                "db_table": "investmentstransfers",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="investmentsoperations",
            name="associated_it",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="moneymoney.investmentstransfers",
            ),
        ),
    ]
