# Generated by Django 5.2.7 on 2025-10-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "moneymoney",
            "0061_alter_strategiesproductsrange_recomendation_method_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accountsoperations",
            name="refund_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunds",
                to="moneymoney.accountsoperations",
            ),
        ),
    ]
