# Generated by Django 5.2.7 on 2025-11-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0062_accountsoperations_refund_original_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixtureVersion",
            fields=[
                (
                    "name",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("md5_hash", models.CharField(max_length=32)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "fixture_version",
                "managed": True,
            },
        ),
    ]
