# Generated by Django 6.0 on 2025-12-18 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0062_accountsoperations_refund_original_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountstransfers",
            name="ao_commission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ao_commission",
                to="moneymoney.accountsoperations",
            ),
        ),
        migrations.AlterField(
            model_name="accountstransfers",
            name="ao_destiny",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ao_destiny",
                to="moneymoney.accountsoperations",
            ),
        ),
        migrations.AlterField(
            model_name="accountstransfers",
            name="ao_origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ao_origin",
                to="moneymoney.accountsoperations",
            ),
        ),
    ]
