# Generated by Django 6.0.2 on 2026-03-03 20:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moneymoney", "0063_alter_accountstransfers_ao_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investmentstransfers",
            name="price_destiny",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=100,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="investmentstransfers",
            name="price_origin",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=100,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="investmentstransfers",
            name="shares_destiny",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="investmentstransfers",
            name="shares_origin",
            field=models.DecimalField(decimal_places=6, max_digits=100),
        ),
    ]
