# Generated by Django 6.0.4 on 2026-04-14 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0064_alter_investmentstransfers_price_destiny_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardsoperations',
            name='accountsoperations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='paid_accountsoperations', to='moneymoney.accountsoperations'),
        ),
    ]
