# Generated by Django 6.0.6 on 2026-07-17 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0065_alter_creditcardsoperations_accountsoperations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='moneymoney.products'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
