# Generated by Django 6.1 on 2026-09-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneymoney', '0066_alter_quotes_datetime_alter_quotes_products_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['banks', 'active'], name='acc_bank_active_idx'),
        ),
        migrations.AddIndex(
            model_name='accounts',
            index=models.Index(fields=['active'], name='acc_active_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsoperations',
            index=models.Index(fields=['accounts', 'datetime'], name='accops_acc_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='accountsoperations',
            index=models.Index(fields=['datetime'], name='accops_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='banks',
            index=models.Index(fields=['active'], name='banks_active_idx'),
        ),
        migrations.AddIndex(
            model_name='creditcardsoperations',
            index=models.Index(fields=['creditcards', 'paid'], name='ccops_card_paid_idx'),
        ),
        migrations.AddIndex(
            model_name='dividends',
            index=models.Index(fields=['investments', 'datetime'], name='div_inv_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='dps',
            index=models.Index(fields=['products', 'date'], name='dps_prod_date_idx'),
        ),
        migrations.AddIndex(
            model_name='estimationsdps',
            index=models.Index(fields=['products', 'year'], name='estdps_prod_year_idx'),
        ),
        migrations.AddIndex(
            model_name='investments',
            index=models.Index(fields=['active', 'accounts'], name='inv_active_acc_idx'),
        ),
        migrations.AddIndex(
            model_name='investments',
            index=models.Index(fields=['products'], name='inv_products_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentsoperations',
            index=models.Index(fields=['investments', 'datetime'], name='invops_inv_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentsoperations',
            index=models.Index(fields=['datetime'], name='invops_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='investmentstransfers',
            index=models.Index(fields=['datetime_destiny'], name='invtrans_dt_dest_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['executed', 'expiration'], name='orders_exec_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='orders',
            index=models.Index(fields=['investments', 'executed'], name='orders_inv_exec_idx'),
        ),
        migrations.AddIndex(
            model_name='quotes',
            index=models.Index(fields=['products', 'datetime'], name='quotes_prod_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='quotes',
            index=models.Index(fields=['datetime'], name='quotes_dt_idx'),
        ),
    ]
