from django.utils.translation import gettext_lazy as _
_('AMEX Stock Exchange')
_('Account')
_('Added shares')
_('Adjustments. Negative')
_('Adjustments. Positive')
_('Amsterdam Stock Exchange')
_('Attendance bonus')
_('Bank commissions')
_('Belgium Stock Exchange')
_('Bonds. Coupon collection')
_('Bonds. Running coupon collection')
_('Bonds. Running coupon payment')
_('CFD')
_('Cash')
_('Credit card billing')
_('Credit card refund')
_('Currency')
_('Custody commission')
_('Deposit')
_('Derivative management')
_('Derivatives. Daily adjustment')
_('Derivatives. Daily guarantee')
_('Derivatives. Operation commission')
_('Derivatives. Swaps')
_('Dividends')
_('Dividends. Sale of rights')
_('Dublin Stock Exchange')
_('ETF')
_('Europe Stock Exchange')
_('Expense')
_('Fast investments operations')
_('Fast operations')
_('Frankfurt Stock Exchange')
_('Fund')
_('Future')
_('Gasoline')
_('Helsinki Stock Exchange')
_('Hong Kong Stock Exchange')
_('Income')
_('Index')
_('Initiating bank account')
_('Leisure')
_('Leverage x10')
_('Leverage x100')
_('Leverage x1000')
_('Leverage x2')
_('Leverage x20')
_('Leverage x200')
_('Leverage x25')
_('Leverage x3')
_('Leverage x4')
_('Leverage x5')
_('Leverage x50')
_('Leverage x500')
_('Lisbon Stock Exchange')
_('London Stock Exchange')
_('Luxembourg Stock Exchange')
_('Madrid Stock Exchange')
_('Milan Stock Exchange')
_('NYSE Stock Exchange')
_('Nasdaq Stock Exchange')
_('Not listed on official markets')
_('Paris Stock Exchange')
_('Paysheet')
_('Pension plan')
_('Personal Management')
_('Private bond')
_('Public bond')
_('Purchase investment product')
_('Purchase of shares')
_('Restaurant')
_('Rollover Paid')
_('Rollover Received')
_('Sale investment product')
_('Sale of shares')
_('Share')
_('Shares addition')
_('Supermarket')
_('Taxes. Paid')
_('Taxes. Returned')
_('Tokyo Stock Exchange')
_('Transfer of funds')
_('Transfer of shares destiny')
_('Transfer of shares origin')
_('Transfer')
_('Transfer. Destination')
_('Transfer. Origin')
_('Unknown')
_('Variable leverage')
_('Warrant')
_('Without leverage')
