from django.utils.translation import gettext_lazy as _
_('Added shares')
_('Adjustments. Negative')
_('Adjustments. Positive')
_('Attendance bonus')
_('Bank commissions')
_('Bonds. Coupon collection')
_('Bonds. Running coupon collection')
_('Bonds. Running coupon payment')
_('Credit card billing')
_('Credit card refund')
_('Custody commission')
_('Derivatives. Daily adjustment')
_('Derivatives. Daily guarantee')
_('Derivatives. Operation commission')
_('Derivatives. Swaps')
_('Dividends')
_('Dividends. Sale of rights')
_('Gasoline')
_('Initiating bank account')
_('Leisure')
_('Paysheet')
_('Purchase investment product')
_('Restaurant')
_('Rollover Paid')
_('Rollover Received')
_('Sale investment product')
_('Supermarket')
_('Taxes. Paid')
_('Taxes. Returned')
_('Transfer. Destination')
_('Transfer. Origin')
_('Unknown')
_('Leverage x10')
_('Leverage x100')
_('Leverage x100')
_('Leverage x2')
_('Leverage x20')
_('Leverage x200')
_('Leverage x25')
_('Leverage x3')
_('Leverage x4')
_('Leverage x5')
_('Leverage x50')
_('Leverage x500')
_('Variable leverage')
_('Without leverage')
_('Account')
_('CFD')
_('Currency')
_('Deposit')
_('ETF')
_('Fund')
_('Future')
_('Index')
_('Pension plan')
_('Private bond')
_('Public bond')
_('Share')
_('Warrant')
_('Credit card billing')
_('Derivative management')
_('Expense')
_('Income')
_('Purchase of shares')
_('Sale of shares')
_('Shares addition')
_('Transfer')
_('Transfer of funds')
_('Transfer of shares destiny')
_('Transfer of shares origin')
_('Cash')
_('Personal management')
