ALTER TABLE public.dps ALTER COLUMN date SET NOT NULL;
ALTER TABLE public.dps ALTER COLUMN paydate SET NOT NULL;
ALTER TABLE public.dps ALTER COLUMN gross SET NOT NULL;
ALTER TABLE public.dps ALTER COLUMN products_id SET NOT NULL;
ALTER TABLE public.dps ALTER COLUMN paydate DROP DEFAULT;

