name: Django CI

on:
  push:
    branches: [ "main", "104-fix-github-actions" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install postgresql with plpython3u (old migrations)
      run: |
        sudo apt-get update
        sudo apt-get install postgresql-plpython3
    - name: Install python dependencies ${{ matrix.python-version }}
      run: |
        pip install .
    - name: Run Tests
      run: |
        #sudo apt-get --fix-broken
        #sudo apt-get --ignore-missing install postgresql-plpython3
        python manage.py test
