name: Docker Image CI

on:
  push:
    branches: [ "main", "230-publish-docker-after-each-commit" ] # Se ejecuta en cada push a las ramas 'main' o 'master'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      id: build_image # Añadimos un ID para referenciar las salidas de esta acción
      uses: docker/build-push-action@v4
      with:
        context: . # El contexto de construcción es el directorio actual del repositorio
        push: true # Indica que la imagen debe ser publicada (pushed)
        tags: ${{ secrets.DOCKER_USERNAME }}/django_moneymoney:latest # Etiqueta la imagen con tu usuario de Docker Hub y el nombre de la imagen
        file: ./Dockerfile # Especifica la ruta a tu Dockerfile
        # Opcional: Si quieres que el tag sea una salida explícita, aunque 'tags' ya lo define
        # outputs: type=image,names=${{ secrets.DOCKER_USERNAME }}/django_moneymoney:latest,push-by-digest=true

    - name: Save image tag for downstream workflows
      run: echo "${{ secrets.DOCKER_USERNAME }}/django_moneymoney:latest" > image_tag.txt

    - name: Upload image tag artifact
      uses: actions/upload-artifact@v3
      with:
        name: image-tag
        path: image_tag.txt